spring.application.name=EzpayApp

server.port=8081

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE?oracle.jdbc.timezoneAsRegion=false
spring.datasource.username=system
spring.datasource.password=avinash
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true