spring.application.name=EzPay

# Replace these example settings with your actual Oracle connection details.
spring.datasource.url=jdbc:oracle:thin:@//localhost:1522/xepdb1
spring.datasource.username=system
spring.datasource.password=tiger
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
